###############################################################
#
#          欢迎使用XiaoEnchant - 逍式附魔
#
###############################################################
version: 1.1.0

#附魔最大值 32767
maxLevel: 32767
